#!/usr/bin/env python3
"""Generate deepsky_auto.json: a deepsky_pipeline manifest row for every sky-worthy
image in _raw/potm (the ESA/Webb POTM + hand-picked pulls, see scripts/fetch_potm.py).

Classification is keyword-on-title (planet > field > object, first match wins), with
first-guess placement params per class — same philosophy as the hand-tuned MANIFEST
rows: they render fine and get nudged on device. Engineering/PR shots (rocket liftoff,
detector mosaics, side-by-side comparisons) are skipped outright.

Also emits deepsky_auto_catalog.swift — the SpatialImageEnvironment.catalog lines —
so the Swift registry can be pasted, not hand-typed.

Run:  python3 upscale/potm_auto_manifest.py     # rewrites both outputs, prints a table
"""
import html
import json
import os
import re

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
POTM = os.path.join(REPO, "Float/Resources/Textures/_raw/potm")
MANIFEST = os.path.join(POTM, "potm_manifest.json")
OUT_JSON = os.path.join(HERE, "deepsky_auto.json")
OUT_SWIFT = os.path.join(HERE, "deepsky_auto_catalog.swift")

Image.MAX_IMAGE_PIXELS = None

# Non-sky imagery: engineering, alignment, PR. Never scenes.
SKIP = {
    "potm2201a": "rocket liftoff photo",
    "potm2202a": "mirror-alignment detector mosaic",
    "potm2205a": "MIRI/Spitzer side-by-side comparison panel",
    "potm2206":  "FGS engineering test mosaic",
}

PLANET_KW = ("saturn", "jupiter", "uranus", "neptune", "titan ")
FIELD_KW = ("nebula", "cloud", "cliffs", "pillars", "region", "complex", "perseus",
            "sagittarius", "rho ophiuchi", "dust", "n79", "star-forming", "star formation",
            "nursery", "serpens", "orion", "carina", "tarantula", "chamaeleon", "digel",
            "protostar", "westerlund", "ism", "hourglass", "l1527", "herbig")
# params per class — fields fill the forward view, objects hang in the void (§ deepsky
# pipeline docstring; numbers bracket the device-approved hand-tuned rows).
PARAMS = {
    "planet": dict(fov_x=45,  lon=0, lat=0, feather=0.12, exposure=0.2),
    "field":  dict(fov_x=130, lon=0, lat=0, feather=0.30, exposure=0.35),
    "object": dict(fov_x=85,  lon=0, lat=0, feather=0.14, exposure=0.25),
}


def classify(title):
    t = title.lower()
    if any(k in t for k in PLANET_KW):
        return "planet"
    if any(k in t for k in FIELD_KW):
        return "field"
    return "object"


def main():
    with open(MANIFEST) as f:
        entries = json.load(f)
    # Scenes pruned in device triage (scripts/prune_scenes.py) — never resurrect.
    pruned_path = os.path.join(HERE, "pruned_scenes.json")
    pruned = set(json.load(open(pruned_path))) if os.path.exists(pruned_path) else set()
    rows, skipped = [], []
    for e in entries:
        pid = e["id"]
        title = html.unescape(e["title"]).strip()
        if pid in pruned:
            skipped.append((pid, "pruned in device triage"))
            continue
        if pid in SKIP:
            skipped.append((pid, SKIP[pid]))
            continue
        ext = os.path.splitext(e["url"].split("?")[0])[1] or ".tif"
        src = os.path.join(POTM, pid + ext)
        if not os.path.exists(src):
            skipped.append((pid, "file missing"))
            continue
        with Image.open(src) as im:
            w, h = im.size
        cls = classify(title)
        kind = "object" if cls == "planet" else cls
        p = dict(PARAMS[cls])
        if cls == "field" and h > w * 1.1:
            p["rot"] = 1          # vertically-composed field -> horizontal nebula bank
        # Wide panoramics must WRAP into immersive environments, not letterbox (device
        # feedback 2026-07-24, second round: partial 147-159 wraps still read as cut
        # off). Any wide master — object or field — becomes a wrap-field: >=180deg of
        # equidistant wrap at ~80deg vertical, growing with aspect up to 270.
        ar = (max(w, h) if p.get("rot") else w) / (min(w, h) if p.get("rot") else h)
        if cls != "planet" and ar >= 1.9:
            kind = "field"
            p.update(fov_x=max(180, min(270, round(80 * ar))),
                     feather=0.30, exposure=0.35)
        rows.append({"name": f"spatial_{pid}", "rel": f"../potm/{pid}{ext}",
                     "kind": kind, "params": p, "title": title})
        print(f"{pid:<30} {cls:<7} {w}x{h}  {title[:58]}")

    with open(OUT_JSON, "w") as f:
        json.dump(rows, f, indent=1)

    with open(OUT_SWIFT, "w") as f:
        f.write("// Auto-generated by upscale/potm_auto_manifest.py — POTM catalog entries.\n")
        for r in rows:
            t = r["title"].replace('"', "'")
            t = re.sub(r"\s*\((?:NIRCam|MIRI)[^)]*\)$", "", t)  # trim instrument suffixes
            if len(t) > 44:
                t = t[:43].rstrip() + "…"
            f.write(f'        .init(name: "{r["name"]}", title: "{t}", grounded: false),\n')

    print(f"\n{len(rows)} rows -> {OUT_JSON}")
    for pid, why in skipped:
        print(f"SKIPPED {pid}: {why}")


if __name__ == "__main__":
    main()
